### ISSUE TITLE
Github Pages化

### ISSUE THREAD

**Issue by yumetodo** [Kasugaccho/DungeonPicture#1]
Github Pages化するとURLが短くなるし、それ以前に現状のURLは画像ファイルになってないので

`https://github.com/Kasugaccho/DungeonPicture/blob/master/Picture/Logo/logo_color640.gif`
->`https://Kasugaccho.github.io/DungeonPicture/Picture/Logo/logo_color640.gif`

**Comment by AsPJT** [comment]
そうなんですね。
初めて知りました。

**Comment by yumetodo** [comment]
確認できました。こちらはcloseして、これを受けた修正が
https://github.com/Kasugaccho/DungeonTemplateLibrary/pull/6
です
